import assert from 'node:assert/strict';import test from 'node:test';import {fetchReport,fetchCurrentStocks,fetchProductCard,fetchPrices,fetchSupplies,fetchPriceTask} from '../src/wb-api.js';
const response=(body,status=200)=>({ok:status===200,status,json:async()=>body});
test('постранично загружает отчёт без токена в URL',async()=>{const calls=[];const pages=[[{rrd_id:1},{rrd_id:2}],[{rrd_id:3}]];const rows=await fetchReport({token:'secret',dateFrom:'2026-08-01',dateTo:'2026-08-02',pageLimit:2,fetchImpl:async(url,opt)=>{calls.push([String(url),opt]);return response(pages.shift())}});assert.equal(rows.length,3);assert.match(calls[1][0],/rrdid=2/);assert.doesNotMatch(calls[0][0],/secret/);assert.equal(calls[0][1].headers.Authorization,'Bearer secret')});
test('нормализует новый camelCase-отчёт финансов',async()=>{const rows=await fetchReport({token:'x',dateFrom:'2026-08-01',dateTo:'2026-08-02',fetchImpl:async()=>response([{rrdId:1,nmId:12,sku:'4600',vendorCode:'A',docTypeName:'Продажа',retailAmount:'100',forPay:'70',deliveryService:'5'}])});assert.equal(rows[0].nm_id,12);assert.equal(rows[0].barcode,'4600');assert.equal(rows[0].ppvz_for_pay,'70')});
test('отклоняет неверные даты и права',async()=>{await assert.rejects(fetchReport({token:'x',dateFrom:'bad',dateTo:'2026-01-01'}),/дата/);await assert.rejects(fetchReport({token:'x',dateFrom:'2026-01-02',dateTo:'2026-01-01'}),/позже/);await assert.rejects(fetchReport({token:'x',dateFrom:'2026-01-01',dateTo:'2026-01-01',fetchImpl:async()=>response({},403)}),/Финансы/)});
test('при отказе нового API пробует старый токен Статистики',async()=>{const calls=[];const rows=await fetchReport({token:'old',dateFrom:'2026-01-01',dateTo:'2026-01-01',fetchImpl:async(url,opt)=>{calls.push([String(url),opt]);return calls.length===1?response({},403):response([{rrd_id:7}])}});assert.equal(rows.length,1);assert.match(calls[0][0],/finance-api/);assert.match(calls[1][0],/statistics-api/);assert.equal(calls[1][1].method,undefined)});
test('понятно объясняет лимит WB',async()=>{await assert.rejects(fetchReport({token:'x',dateFrom:'2026-01-01',dateTo:'2026-01-01',fetchImpl:async()=>response({},429)}),/Лимит запросов WB/)});
test('нормализует текущие остатки из Analytics API',async()=>{const calls=[];const rows=await fetchCurrentStocks({token:'analytics-secret',nmIds:['12',12],fetchImpl:async(url,opt)=>{calls.push([String(url),opt]);return response({data:[{nmId:12,barcode:'b',warehouseName:'Коледино',quantity:7,inWayToClient:2}]})}});assert.equal(calls.length,1);assert.deepEqual(JSON.parse(calls[0][1].body),{nmIds:[12],chrtIds:[],limit:1000,offset:0});assert.deepEqual(rows[0],{nmId:'12',barcode:'b',warehouse:'Коледино',quantity:7,inWayToClient:2,inWayFromClient:0,updatedAt:null})});
test('раскрывает вложенные остатки по складам',async()=>{const rows=await fetchCurrentStocks({token:'x',nmIds:[12],fetchImpl:async()=>response({data:{items:[{nmId:12,barcode:'b',warehouses:[{warehouseName:'Коледино',quantity:7}]}]}})});assert.equal(rows.length,1);assert.equal(rows[0].warehouse,'Коледино');assert.equal(rows[0].quantity,7)});
test('получает фотографии карточки только по запросу',async()=>{const card=await fetchProductCard({token:'content-secret',nmId:12,fetchImpl:async(url,opt)=>{assert.match(String(url),/content\/v2\/get\/cards\/list/);return response({cards:[{nmID:12,title:'Товар',photos:[{big:'https://img.example/big.jpg'},{c516x688:'https://img.example/medium.jpg'}]}]})}});assert.deepEqual(card,{nmId:'12',title:'Товар',photos:['https://img.example/big.jpg','https://img.example/medium.jpg']})});
test('не подменяет карточку при неточном совпадении nmID',async()=>{const result=await fetchProductCard({token:'x',nmId:999888777,fetchImpl:async()=>response({cards:[{nmID:111222333,title:'Чужой товар',photos:[{big:'https://img.example/other.jpg'}]}]})});assert.equal(result.title,'');assert.deepEqual(result.photos,[])})
test('загружает цены по актуальному контракту WB',async()=>{let request;const rows=await fetchPrices({token:'price-secret',nmIds:['12',12],fetchImpl:async(url,opt)=>{request={url:String(url),opt};return response({data:{listGoods:[{nmID:12,vendorCode:'A-12',discount:30,clubDiscount:5,sizes:[{price:1000,discountedPrice:700,clubDiscountedPrice:665}]}]}})}});assert.deepEqual(JSON.parse(request.opt.body),{nmList:[12]});assert.equal(rows[0].price,1000);assert.equal(rows[0].discountedPrice,700);assert.equal(rows[0].clientPrice,665)});
test('загружает весь каталог цен без предварительного аудита',async()=>{const calls=[];const rows=await fetchPrices({token:'price-secret',fetchImpl:async(url,opt)=>{calls.push([String(url),opt]);return response({data:{listGoods:[{nmID:77,sizes:[{price:500}]}]}})}});assert.equal(calls[0][1].method,undefined);assert.match(calls[0][0],/limit=1000&offset=0/);assert.equal(rows[0].nmId,'77')});
test('не продолжает листать полный каталог без аудита',async()=>{let calls=0;const rows=await fetchPrices({token:'x',fetchImpl:async()=>{calls++;return response({data:{listGoods:Array.from({length:1000},(_,i)=>({nmID:i+1}))}})}});assert.equal(calls,1);assert.equal(rows.length,1000)});
test('передаёт даты поставок в формате ISO Date',async()=>{let body;const result=await fetchSupplies({token:'supply-secret',dateFrom:'2026-08-01',dateTo:'2026-08-28',fetchImpl:async(url,opt)=>{body=JSON.parse(opt.body);return response([])}});assert.deepEqual(body,{dates:[{from:'2026-08-01',till:'2026-08-28',type:'factDate'}]});assert.equal(result.rows.length,0)});
test('проверяет обработанную загрузку цены по uploadID',async()=>{const task=await fetchPriceTask({token:'x',uploadID:15,fetchImpl:async url=>{assert.match(String(url),/history\/goods\/task/);return response({data:{historyGoods:[{nmID:12,status:3,errorText:''}]}})}});assert.equal(task.stage,'processed');assert.equal(task.goods[0].status,3)});
